### ENV vars

# $ENV_VAR_GISTO_VERSION
# $ENV_VAR_GISTO_CLIENT_ID
# $ENV_VAR_GISTO_CLIENT_SECRET
# $ENV_VAR_GISTO_SERVER_TOKEN
# $ENV_VAR_GISTO_NIGHTLY_SERVER
# $ENV_VAR_GISTO_NIGHTLY_SERVER_USER
# $ENV_VAR_GISTO_NIGHTLY_SERVER_PASS

language: node_js

node_js:
- '0.11'

env:
  global:
  - ENV_VAR_GISTO_VERSION="0.2.6b"

branches:
  only:
  - feature/travis-ci

install:
- npm install gulp bower --global
- sudo apt-get install sshpass

before_script:
- npm install
- gulp version_bump --to=$ENV_VAR_GISTO_VERSION
- gulp dist
- chmod +x ./build/script/node-webkit-build.sh
- "export GISTO_TRAVIS_COMMIT_MESSAGE=\"$(git log --format=%B --no-merges -n 1)\""
- "export GISTO_DATE_NOW=\"$(date +\"%Y%m%d\")\""
- echo "{\"client_id\":\"$ENV_VAR_GISTO_CLIENT_ID\",\"client_secret\":\"$ENV_VAR_GISTO_CLIENT_SECRET\",\"server_token\":\"$ENV_VAR_GISTO_SERVER_TOKEN\"}" >> $TRAVIS_BUILD_DIR/dist/config.json

script:
- ./build/script/node-webkit-build.sh --src=$TRAVIS_BUILD_DIR/dist --name=gisto --win-icon=$TRAVIS_BUILD_DIR/app/icon.ico --osx-icon=$TRAVIS_BUILD_DIR/build/resources/osx/gisto.icns --osx-plist=$TRAVIS_BUILD_DIR/build/resources/osx/Info.plist --build

after_success:
- "printf \"### git commit: $TRAVIS_COMMIT\n\n$GISTO_TRAVIS_COMMIT_MESSAGE\n\n[See on GitHub](https://github.com/Gisto/Gisto/commit/$TRAVIS_COMMIT)\" >> ./build/script/TMP/output/_h5ai.header.md"
- cd ./build/script/TMP
- mv output $GISTO_DATE_NOW
- ln -s $GISTO_DATE_NOW latest
- ncftpput -R -v -u "$ENV_VAR_GISTO_NIGHTLY_SERVER_USER" -p "$ENV_VAR_GISTO_NIGHTLY_SERVER_PASS" $ENV_VAR_GISTO_NIGHTLY_SERVER public_html_BKP $GISTO_DATE_NOW
- sshpass -p "$ENV_VAR_GISTO_NIGHTLY_SERVER_PASS" rsync -av latest $ENV_VAR_GISTO_NIGHTLY_SERVER_USER@$ENV_VAR_GISTO_NIGHTLY_SERVER:/home/gistoapp/public_html_BKP/

#- curl -T latest $ENV_VAR_GISTO_NIGHTLY_SERVER/public_html_BKP --user $ENV_VAR_GISTO_NIGHTLY_SERVER_USER:$ENV_VAR_GISTO_NIGHTLY_SERVER_PASS