language: node_js
node_js:
  - "0.11"

# whitelist
branches:
  only:
    - feature/travis-ci

before_install:
  - sudo apt-get install -y nsis

install:
  - cd build
  - chmod -x ./release.sh
  - ./release.sh --all v0.2.6b

