language: node_js
node_js:
  - "0.11"

# whitelist
branches:
  only:
    - feature/travis-ci

install:
  - sudo apt-get install -y nsis

after_install:
  - chmod -x ./build/release.sh

script: ./build/release.sh --all v0.2.6b

